spring:
  profiles:
    active: local
  datasource:
    hikari:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:sqlserver://localhost:1433
      username: SA
      password: heejoong123!